Feature/weui beta
weui/react-weui pull request #323
Opened 2020-08-02 13:10 UTC by z2014

update version 2.0
1. update components button support ts
2. update webpack 4
3. update rollup plugin

2020-08-03 04:24 UTC, aquariuslt requested changes
## 重点

> 不在行内提建议了哈，因为有一些代码需要新增，不在已修改的文件集合中。

1. CI Fail
    CI 失败主要是因为执行单元测试 使用的是 mocha，在升级 babel 版本后，原本的 `babel-core/register` 依赖被删除了，如需保持 CI 正常运行(继续使用mocha)，需要做以下工作:
     1.1. 安装依赖 `@babel/register`
     1.2. 更新项目中的 `test/mocha.opts` ，将旧版的 babel register 更新为 `--require @babel/core` 和 `--require @babel/register` 两行
    1.3. `yarn coverage` 所执行的 `nyc` require 部分也要修改， `babel-core/register` 参考 1.2 内容进行修改

2. Webpack
   webpack升级到4之后，部分 production 配置需要修改，这里根据构建时提示修改去除 warning 

3. Rollup build script
- 移除部分调试用的 `console.log`
- 执行 `yarn build` 并没有很好的把 production 相关配置传递进去，构建出来少了 `.min`版本的内容
- 这里的修改请对比前几个版本的构建产物目录，可在 [https://cdn.unix.bio/?q=react-weui&npm=1](https://cdn.unix.bio/?q=react-weui&npm=1) 中对比 1.1.x ~ 1.2.3 之间的产物发布目录

## 其他

1. eslint 样式问题，`npm scripts - lint` 的部分，应当包含新增的 `components/**/*.ts tsx`  路径
2. 修复新增的 `ts/tsx` 文件带来的风格问题，如双引号->单引号等

2020-08-03 12:34 UTC, Rlilyyy commented on components/button/src/button.tsx
> +const Button = React.forwardRef(InternalButton);
这里使用 `React.forwardRef` 的意义是？

2020-08-03 12:40 UTC, Rlilyyy commented on components/button/src/interface.ts
> +
这里面的 ts 变量声明，每个 prop 都是选填的？如果是必填应该声明为 `Prop: Type`，而不是 `Prop?: Type`

2020-08-03 12:44 UTC, Rlilyyy commented on example/index.html
> +    <link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/2.4.0/weui.min.css">
使用 `<link>` 引入 2.0 样式，而不是跟以前的 `import` 引入的原因是？

2020-08-03 12:44 UTC, z2014 commented on components/button/src/interface.ts
> +
都是选填的，最简单的引入如下：
`<Button>Normal</Button>`

2020-08-03 12:51 UTC, z2014 commented on example/index.html
> +    <link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/2.4.0/weui.min.css">
一开始mock用的，应该改回来

2020-08-04 03:32 UTC, z2014 commented on components/button/src/button.tsx
> +const Button = React.forwardRef(InternalButton);
透传 ref, 已补充

2020-08-04 13:28 UTC, aquariuslt commented on package.json
> +    "autofix": "./node_modules/.bin/eslint components --ext .ts,.tsx --fix",
```suggestion
    "lint": "eslint components --ext .ts,.tsx",
    "autofix": "eslint components --ext .ts,.tsx --fix",
```

2020-08-04 13:32 UTC, aquariuslt commented on webpack.config.doc.js
> +  // );
建议直接删

2020-08-04 13:33 UTC, aquariuslt commented on webpack.config.js
> +  // );
同上

2020-08-06 13:40 UTC, aquariuslt approved these changes
LGTM

2020-08-06 14:23 UTC, merged